spring:
  application:
    name: supplier-service

  datasource:
    url: jdbc:postgresql://localhost:5432/supplierdb
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 7070

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

